#!/bin/bash
#PBS -l walltime=100:00:00
#PBS -e error.txt
#PBS -o output.txt
#PBS -V
cd /home/alex/UG-RNN/ugrnn
./ugrnnTrain -d delaney-logP -t delaney-logP -f 6 -m 0 -vl > ./test/delaney-logP/fold6/model0/logModel0